client_config_backend: settings
client_config:
  client_id: 1028552406701-otf52nsb3cnvmelojpsasgmb18m4osga.apps.googleusercontent.com
  client_secret: XuJVa3uSjBNCKERuYkLaj50K

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata